// ========================================
// Coding Agent
// =========================================

import { askAI } from "../ai.js";
import { commitFile } from "../tools/github.js";

function stripCodeFences(text) {
  return text
    .replace(/^```[\w]*\n/, "")
    .replace(/```$/, "")
    .trim();
}

export async function runCodingAgent(env, { path, instructions }) {

  const messages = [
    {
      role: "system",
      content:
        "You are a coding agent. Output ONLY the raw code for the requested file. No explanations, no markdown code fences, no commentary before or after the code.",
    },
    {
      role: "user",
      content: `Write the complete code for the file "${path}".\n\nInstructions:\n${instructions}`,
    },
  ];

  const rawCode = await askAI(env, messages);
  const code = stripCodeFences(rawCode);

  const result = await commitFile(
    env,
    path,
    code,
    `Coding Agent: update ${path}`
  );

  return {
    path,
    committed: true,
    commitUrl: result.commit.html_url,
  };

}

// -----------------------------------------
// Multi-file Coding Agent
// -----------------------------------------

const PLANNER_BASE_PROMPT =
  'You are a software planner. Given a project description, output ONLY a JSON array of file plans. Each item must have "path" (string, relative repo path) and "instructions" (string, a CONCISE 1-2 sentence instruction for that specific file — do not write long detailed instructions, keep the whole JSON short). ONLY plan text-based code files (.html, .css, .js, .json, .md). NEVER plan binary/image files (.png, .jpg, .ico, .svg, .gif, .mp3, .wav) — if icons or graphics are needed, instruct the file to use CSS shapes, unicode/emoji characters, or inline SVG markup instead. No explanations, no markdown fences, just raw JSON. Keep it to 2-5 files.';

async function requestPlan(env, projectDescription, extraNote = "") {

  const messages = [
    {
      role: "system",
      content: PLANNER_BASE_PROMPT + extraNote,
    },
    {
      role: "user",
      content: `Project: ${projectDescription}`,
    },
  ];

  const rawPlan = await askAI(env, messages, { max_tokens: 1500 });
  return stripCodeFences(rawPlan);

}

async function planFiles(env, projectDescription) {

  let cleanPlan = await requestPlan(env, projectDescription);
  let files;

  try {
    files = JSON.parse(cleanPlan);
  } catch {

    // --- Self-healing retry: প্রথমবার ভুল/অসম্পূর্ণ JSON হলে একবার আবার চেষ্টা ---
    console.log("Planner JSON parse failed, retrying once with a stricter note...");

    cleanPlan = await requestPlan(
      env,
      projectDescription,
      "\n\nIMPORTANT: Your previous response was not valid JSON or was cut off. Return ONLY a complete, valid, properly closed JSON array. Keep every instruction to a single short sentence so the full response fits."
    );

    try {
      files = JSON.parse(cleanPlan);
    } catch {
      throw new Error("Planner did not return valid JSON after retry: " + cleanPlan.slice(0, 200));
    }

  }

  if (!Array.isArray(files) || files.length === 0) {
    throw new Error("Planner returned an empty or invalid file list");
  }

  // --- ডিফেন্স: planner ভুলে বাইনারি/ইমেজ ফাইল প্ল্যান করলে বাদ দেওয়া ---
  const BINARY_EXT = /\.(png|jpe?g|gif|ico|svg|webp|bmp|mp3|wav|ogg|pdf|zip|woff2?|ttf)$/i;
  const skipped = files.filter((f) => BINARY_EXT.test(f.path));
  files = files.filter((f) => !BINARY_EXT.test(f.path));

  if (skipped.length > 0) {
    console.log("Skipped binary files planner tried to create:", skipped.map(f => f.path));
  }

  if (files.length === 0) {
    throw new Error("Planner only returned binary/image files, which cannot be generated by a text LLM");
  }

  return files;

}

export async function runMultiFileCodingAgent(env, { projectDescription, folder }) {

  const plan = await planFiles(env, projectDescription);

  const results = [];

  for (const file of plan) {

    const fullPath = folder
      ? `${folder}/${file.path}`.replace(/\/+/g, "/")
      : file.path;

    try {

      const result = await runCodingAgent(env, {
        path: fullPath,
        instructions: file.instructions,
      });

      results.push({ ...result, success: true });

    } catch (err) {

      results.push({
        path: fullPath,
        success: false,
        error: err.message,
      });

    }

  }

  return {
    plan,
    results,
  };

}
