name: Deploy Worker

on:
  push:
    branches: [ main ]
    paths:
      - 'worker/**'  # শুধু worker ফোল্ডার চেঞ্জ হলে deploy হবে

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20' # wrangler v3 এর জন্য 20 লাগবে
      
      - name: Install Wrangler
        run: npm install -g wrangler@3
        
      - name: Deploy to Cloudflare
        run: wrangler deploy --x-remote
        working-directory: ./worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
